project:
  type: website
  output-dir: docs
  
website:
  title: "Luca Alioto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research
      - href: blog.qmd
        text: Blog
    tools:
      - icon: github
        href: https://github.com/lucaalioto
      - icon: bluesky
        href: https://bsky.app/profile/lucaalioto.bsky.social
        aria-label: Bluesky
      - icon: twitter
        href: https://x.com/lucaalioto
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "Luca Alioto"

format:
  html:
    theme:
      - sandstone
      - assets/css/custom.scss
    toc: true
    highlight-style: monokai
    
editor: source
