---
title: "Luca Alioto"
subtitle: "Urban Planning Student <br> University of California, Los Angeles <br> ✉️ [jalioto@ucla.edu](mailto:jalioto@ucla.edu)"
toc: false
about: 
  template: trestles
  image-shape: rounded
  image-width: 16em
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/luca-alioto
    - icon: calendar-event
      text: Calendar
      href: https://calendar.notion.so/meet/lucaalioto/4c9jr4ykj
    - icon: file-pdf
      text: CV
      href: assets/cv/AliotoLucaR.pdf
resources:
  - assets/**
---
<style>
.quarto-title h1.title {
  font-size: 1.75em; /* default is larger, adjust to taste */
}
.quarto-title .subtitle {
  font-size: 1.15rem; /* keeps the school name on one line */
}
</style>
### About Me

My name is Luca Alioto, and I'm a first-year Master of Urban and Regional Planning student (or MURP for short!) in the Luskin School of Public Affairs at UCLA. This past spring I completed my undergrad at UC Davis, studying Political Science and Community Development.

My approach to planning and politics lives at the intersection of theory and practice, making me an individual with the hard skills of policy and quantitative human-driven research expertise, created through community and personal engagement; an understanding that comes from passion and involvement.

My current research spans three areas: refining my honors thesis on political violence and democratic backsliding in El Salvador, the development of a manuscript on housing and transportation policy analysis, and research assistant work on job accessibility. 

### Education

**Master of Urban and Regional Planning**<br>
University of California, Los Angeles • June 2028

**BA Political Science & BS Community Development**<br>
University of California, Davis • June 2026 • GPA 3.8

### Research Interests 

Housing & Transportation Equity | Immigration | Ingroup/Outgroup Relations | Economic Development | Labor & Racial Equity | Political Violence & Democratic Backsliding | Mass Incarceration | Media Coverage of Conflict | Socio-economic Inequality 